global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "hospital-appointment"
    metrics_path: "/metrics"
    static_configs:
      # Service name on the docker-compose network
      - targets: ["hospital-app:5000"]
